spring.application.name=crud

server.port=8080


# # ===============================
# # DATASOURCE (SUPABASE - POSTGRES)
# # ===============================
# spring.datasource.url=jdbc:postgresql://db.grqguuuqkbdxwvebbfza.supabase.co:5432/postgres?sslmode=require
# spring.datasource.username=postgres
# spring.datasource.password=Umiabiha@69
# spring.datasource.driver-class-name=org.postgresql.Driver



# # ===============================
# # JPA / HIBERNATE
# # ===============================
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?sslmode=require
# spring.datasource.username=postgres.grqguuuqkbdxwvebbfza
# spring.datasource.password=Umiabiha@69

# spring.datasource.driver-class-name=org.postgresql.Driver

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.grqguuuqkbdxwvebbfza
spring.datasource.password=Umiabiha@69

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.hikari.data-source-properties.prepareThreshold=0
spring.datasource.hikari.data-source-properties.binaryTransfer=false


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=fidawani20022@gmail.com
spring.mail.password=natc sxam hria xbcj

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

supabase.url= https://grqguuuqkbdxwvebbfza.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdycWd1dXVxa2JkeHd2ZWJiZnphIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MDgwNzQ1OSwiZXhwIjoyMDg2MzgzNDU5fQ.fjuv3A5ORn-PayXoi-10BQp_3vIyY7buuvsOnxVl_hY
supabase.bucket = public_Media